package com.example.kidslearningapp.util

import com.example.kidslearningapp.R
import com.example.kidslearningapp.domain.ChallengeCardModel
import com.example.kidslearningapp.domain.LessonPageCardModel
import com.example.kidslearningapp.domain.LessonsModel

object Constant {
    val listChallenge = mutableListOf<ChallengeCardModel>(
        ChallengeCardModel(
            R.string.exam,
            40,
            R.drawable.icon_card_1,
            R.drawable.custom_progress_turquoise
        ),
        ChallengeCardModel(
            R.string.math,
            40,
            R.drawable.icon_card_2,
            R.drawable.custom_progress_orange
        ),
        ChallengeCardModel(
            R.string.arabic,
            40,
            R.drawable.icon_card_3,
            R.drawable.custom_progress_green
        ),
        ChallengeCardModel(
            R.string.science,
            40,
            R.drawable.icon_card_4,
            R.drawable.custom_progress_orange
        ),
        ChallengeCardModel(
            R.string.challenge,
            40,
            R.drawable.icon_card_1,
            R.drawable.custom_progress_green
        ),
        ChallengeCardModel(
            R.string.arts,
            40,
            R.drawable.icon_card_5,
            R.drawable.custom_progress_turquoise
        ),
        ChallengeCardModel(
            R.string.islamic_study,
            40,
            R.drawable.icon_card_6,
            R.drawable.custom_progress_orange
        ),
        ChallengeCardModel(
            R.string.social_science,
            40,
            R.drawable.icon_card_7,
            R.drawable.custom_progress_green
        ),
    )
    val listLessons = mutableListOf(
        LessonPageCardModel(
            R.string.lesson_title_1,
            0,
            R.string.lesson_lectures_1,
            1,
        ),
        LessonPageCardModel(
            R.string.lesson_title_2,
            0,
            R.string.lesson_lectures_2,
            2,
        ),
        LessonPageCardModel(
            R.string.lesson_title_3,
            0,
            R.string.lesson_lectures_3,
            3,
        ),
        LessonPageCardModel(
            R.string.lesson_title_4,
            0,
            R.string.lesson_lectures_4,
            4,
        )
    )

    val lessons = listOf(
        mutableListOf(
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_blue,
                R.string.time_1,
                R.string.lectures_title_1,
                R.drawable.icon_unlock,
                1
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_2,
                R.string.lectures_title_2,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
        ),
        mutableListOf(
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_blue,
                R.string.time_1,
                R.string.lectures_title_1,
                R.drawable.icon_unlock,
                1
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_2,
                R.string.lectures_title_2,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
        ),
        mutableListOf(
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_blue,
                R.string.time_1,
                R.string.lectures_title_1,
                R.drawable.icon_unlock,
                1
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_2,
                R.string.lectures_title_2,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            )
        ),
        mutableListOf(
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_blue,
                R.string.time_1,
                R.string.lectures_title_1,
                R.drawable.icon_unlock,
                1
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_2,
                R.string.lectures_title_2,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
            LessonsModel(
                R.string.lesson_description,
                R.drawable.icon_btn_play_black,
                R.string.time_3,
                R.string.lectures_title_3,
                R.drawable.icon_lock,
                0
            ),
        )
    )
}